const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),{chromium}=require('playwright');
const html=fs.readFileSync(__dirname+'/../test-v0.1.16.html','utf8'),scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);scripts.filter(s=>s.trim()).forEach(s=>new vm.Script(s));
const base=html.slice(html.indexOf('let privateDilemma=null'),html.indexOf('async function openDebateHelpHistory(){'));
const dialogue=scripts.find(s=>s.includes('R93: private dialogue,')),thinking=scripts.find(s=>s.includes('const E=id=>document.getElementById(id),expanded=new Set()')),moderation=scripts.find(s=>s.includes('R105: moderation is authoritative'));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.DILEMA_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fixture.test/',route=>route.fulfill({contentType:'text/html',body:html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'')}));await page.goto('https://fixture.test/');
 await page.evaluate(()=>{
  Object.assign(window,{currentUserId:'fixture',currentRoomId:null,currentRoundId:null,currentRoomMode:'debate',privateSelectionMode:false,setupDebateStyle:'free',setupSpeechSeconds:90,setupStyleChosen:false,savedRows:[],calls:[],profiles:0});
  window.showScreen=id=>document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));window.openProfileChoice=()=>profiles++;window.renderDilemmaCopy=(e,s)=>e.textContent=s;window.guideHistoryCounts=()=>({matching:0,total:0});window.ensureAnonymousAuth=async()=>{};window.syncCharacterCounters=()=>{};
  const field=document.createElement('textarea');field.id='privateContext';const details=document.createElement('details');details.append(field);document.getElementById('privateForm').append(details);
  window.sb={from(table){let insert=null,patch=null;const q={select(){return q},eq(){return q},order(){return q},limit(){return q},insert(v){insert=v;return q},update(v){patch=v;return q},single(){return run()},maybeSingle(){return run()},then(a,b){return run().then(a,b)}};async function run(){if(table==='private_dilemma_sessions'){if(insert){testSession={id:crypto.randomUUID(),...insert};calls.push(['insert',insert])}if(patch)Object.assign(testSession,patch);return {data:{...testSession}}}return {data:table==='private_dilemma_guides'?[]:savedRows.map(x=>({...x}))}}return q},functions:{async invoke(name,{body}){calls.push([name,body]);const t={id:body.requestId,session_id:body.sessionId,turn_number:savedRows.length+1,message:body.message,choice:testSession.choice,status:'ready',reflection:'Respuesta desde la postura contraria.',question:'¿Cómo justificas ese coste?',mode:'IA'};savedRows.push(t);return {data:{status:'ready',turn:t}}}}};
 });
 for(const content of [base,dialogue,thinking,moderation])await page.addScriptTag({content});await page.evaluate(()=>document.dispatchEvent(new Event('DOMContentLoaded')));
 await page.evaluate(()=>openPrivateDilemma());assert.equal(await page.locator('#privateModeChoice').isVisible(),true);
 await page.locator('#privateModeChoice button').filter({hasText:'DEBATIR VS DILEMA'}).click();assert.equal(await page.evaluate(()=>privateInteractionMode),'training');
 await page.evaluate(()=>openPrivateDilemmaForm());assert.equal(await page.locator('#privateOptionalOptions').getAttribute('open'),'');
 await page.locator('#privateFormTeens').click();await page.locator('#privateQuestion').fill('¿Guardas un secreto o pides ayuda?');assert.equal(await page.locator('#privateCreate').isEnabled(),false);
 await page.locator('#privateA').fill('Guardar el secreto');await page.locator('#privateB').fill('Pedir ayuda');assert.equal(await page.locator('#privateCreate').isEnabled(),true);await page.locator('#privateCreate').click();await page.waitForTimeout(80);
 assert.equal(await page.evaluate(()=>testSession.interaction_mode),'training');assert.equal(await page.locator('#privateDialogueTitle').textContent(),'DEBATIR VS DILEMA');assert.equal(await page.evaluate(()=>savedRows.length),0,'Training waits for posture');
 await page.locator('#privateVoteA').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>savedRows.length),1);assert.match(await page.evaluate(()=>calls.at(-1)[1].message),/postura contraria/);
 assert.equal(await page.locator('#privateVoteA').evaluate(e=>getComputedStyle(e).borderColor),'rgb(255, 255, 255)');assert.equal(await page.locator('#privateVoteA').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)','Filled selections keep their original style');assert.equal(await page.locator('#privateDialogueOrder').getAttribute('aria-label'),'VALORA MIS ARGUMENTOS');
 await page.locator('#privateDialogueOrder').click();await page.waitForTimeout(80);assert.match(await page.evaluate(()=>calls.at(-1)[1].message),/razón más sólida/);
 await page.locator('#privatePlanteamientoTitle').click();await page.locator('#privateVoteB').click();await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>testSession.choice),'B');assert.equal(await page.evaluate(()=>savedRows.length),2,'Posture change preserves history');
 await page.evaluate(()=>{openPrivateDilemma();choosePrivateInteraction('reflection');openPrivateDilemmaForm()});assert.match(await page.locator('#privateOptionalOptions summary').textContent(),/OPCIONAL/);
 await page.evaluate(()=>{setupStyleChosen=false;showScreen('debateStyleChoice')});assert.equal(await page.locator('#r107SetupTime').isVisible(),false);assert.equal(await page.locator('#debateStyleChoice .r110-mode.selected').count(),0,'R110 starts with no selected style');assert.equal(await page.locator('#r110StyleContinue').isEnabled(),false);for(const id of ['r110FreeSelect','r107ModeratedSelect']){assert.equal(await page.locator('#'+id).getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#'+id).evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)')}
 await page.locator('#r107ModeratedSelect').click();assert.equal(await page.locator('#r107SetupTime').isVisible(),true);assert.equal(await page.evaluate(()=>profiles),0,'Choosing moderated reveals duration without navigating');assert.equal(await page.locator('#r107ModeratedSelect').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#r110FreeSelect').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#r107ModeratedSelect').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');assert.equal(await page.locator('#r110StyleContinue').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await page.locator('#r110StyleContinue').textContent(),'CONTINUAR');
 await page.locator('[data-setup-seconds="120"]').click();await page.locator('#r110StyleContinue').click();assert.equal(await page.evaluate(()=>setupSpeechSeconds),120);assert.equal(await page.evaluate(()=>profiles),1);
 await page.evaluate(()=>showScreen('debateStyleChoice'));assert.equal(await page.locator('#debateStyleChoice .r110-mode.selected').count(),0,'Returning clears previous style');assert.equal(await page.locator('#r110StyleContinue').isEnabled(),false);
 await page.locator('#r107ModeratedSelect').click();await page.locator('#r110FreeSelect').click();assert.equal(await page.locator('#r107SetupTime').isVisible(),false);assert.equal(await page.evaluate(()=>setupDebateStyle),'free');assert.equal(await page.evaluate(()=>profiles),1,'Free selection also waits for confirmation');assert.equal(await page.locator('#r110FreeSelect').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#r107ModeratedSelect').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#debateStyleChoice .r110-mode.selected').count(),1);await page.locator('#r110StyleContinue').click();assert.equal(await page.evaluate(()=>profiles),2);assert.equal(await page.evaluate(()=>setupStyleChosen),true);assert.equal(await page.evaluate(()=>setupDebateStyle),'free');
 const voting=html.slice(html.indexOf('function renderVoting('),html.indexOf('async function assignRoles('));await page.addScriptTag({content:voting});
 await page.evaluate(()=>{Object.assign(window,{localVoteChoice:'A',currentDilemma:{question:'Prueba',option_a:'A',option_b:'B'},currentExpectedPlayers:2,currentRoomHostId:'host',localPlayerId:'host',assigningRoles:false,currentRoundStatus:'reveal'});renderVoting({total_votes:2,votes_a:1,votes_b:1});renderResult({total_votes:2,votes_a:1,votes_b:1})});
 assert.equal(await page.locator('#voteAButton').evaluate(e=>getComputedStyle(e).borderColor),'rgb(74, 222, 128)');assert.equal(await page.locator('#result .result-item').first().evaluate(e=>getComputedStyle(e).borderColor),'rgb(74, 222, 128)');
 await page.evaluate(()=>{const b=document.createElement('button');b.className='selection-question selected';b.disabled=true;document.getElementById('catalogDilemmas').append(b)});assert.equal(await page.locator('#catalogDilemmas .selected').evaluate(e=>getComputedStyle(e).borderColor),'rgb(74, 222, 128)');
 assert.deepEqual(errors,[]);console.log('PASS R107: individual reflection/training entry, required positions, saved mode, posture-gated kickoff, opponent prompt, feedback action, change posture/history, filled private selections preserved; green preliminary vote/reveal/candidate, progressive moderated time and free navigation; all inline scripts parse; real mobile Chromium clicks');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
