begin;
do $test$
declare room bigint;rd bigint;proposal bigint;x jsonb;n bigint;failed boolean;
 u1 uuid:='00000000-0080-4000-8000-000000000001';
 u2 uuid:='00000000-0080-4000-8000-000000000002';
 u3 uuid:='00000000-0080-4000-8000-000000000003';
begin
 perform set_config('request.jwt.claim.sub',u1::text,true);
 insert into public.rooms(code,host_id,expected_players,mode,status) values('T80Q','r80-host',3,'debate','waiting') returning id into room;
 insert into public.players(room_id,player_id,user_id,name) values(room,'r80-host',u1,'TEST HOST'),(room,'r80-two',u2,'TEST TWO'),(room,'r80-three',u3,'TEST THREE');
 if public.change_lobby_size(room,-1)<>3 then raise exception 'Size below joined count';end if;
 delete from public.players where room_id=room and user_id<>u1;
 if public.change_lobby_size(room,-1)<>2 or public.change_lobby_size(room,-1)<>1 then raise exception 'Cannot reduce to one';end if;
 insert into public.players(room_id,player_id,user_id,name) values(room,'r80-two',u2,'TEST TWO'),(room,'r80-three',u3,'TEST THREE');
 update public.rooms set status='playing',expected_players=3 where id=room;
 insert into public.rounds(room_id,debate_phase,status) values(room,'debate','debate') returning id into rd;
 x:=public.propose_debate_limbo(rd,'r80-two',180);proposal:=(x->>'id')::bigint;
 failed:=false;begin perform public.propose_debate_pause(rd,true);exception when others then failed:=true;end;
 if not failed then raise exception 'Parallel pause was allowed';end if;
 x:=public.get_debate_state(rd);
 if x->'limbo_state'->'proposal'->>'yes'<>'1' then raise exception 'Automatic yes missing';end if;
 perform set_config('request.jwt.claim.sub',u2::text,true);
 x:=public.cast_debate_limbo_vote(rd,proposal,'NO');if x->>'status'<>'open' then raise exception 'Target vote not accepted';end if;
 perform set_config('request.jwt.claim.sub',u3::text,true);
 x:=public.cast_debate_limbo_vote(rd,proposal,'YES');if x->>'status'<>'accepted' then raise exception 'Majority did not accept';end if;
 if not private.limbo_blocked(room,u2) then raise exception 'Limbo not active';end if;
 if not exists(select 1 from public.players where room_id=room and user_id=u2 and presence='absent') then raise exception 'Target still present';end if;
 perform set_config('request.jwt.claim.sub',u2::text,true);
 failed:=false;begin perform public.propose_presence_change(rd,'return',null);exception when others then failed:=true;end;
 if not failed then raise exception 'Early return request was allowed';end if;
 failed:=false;begin perform public.set_debate_presence(room,'present');exception when others then failed:=true;end;
 if not failed then raise exception 'Direct presence bypass allowed';end if;
 update private.debate_limbo_proposals set until_at=clock_timestamp()-interval '1 second' where id=proposal;
 if private.limbo_blocked(room,u2) then raise exception 'Expired limbo blocks';end if;
 perform public.propose_presence_change(rd,'return',null);
 if not exists(select 1 from public.players where room_id=room and user_id=u2 and presence='absent') then raise exception 'Auto return occurred';end if;
 update public.debate_presence_requests set status='rejected' where round_id=rd;
 update public.players set presence='present' where room_id=room and user_id=u2;
 -- The host can be sent to limbo and transfers the role.
 x:=public.propose_debate_limbo(rd,'r80-host',0);proposal:=(x->>'id')::bigint;
 perform set_config('request.jwt.claim.sub',u3::text,true);
 x:=public.cast_debate_limbo_vote(rd,proposal,'YES');
 if x->>'status'<>'accepted' or not private.limbo_blocked(room,u1) then raise exception 'End-debate limbo not applied';end if;
 if exists(select 1 from public.rooms where id=room and host_id='r80-host') then raise exception 'Host not transferred';end if;
 x:=public.cast_debate_limbo_vote(rd,proposal,'NO');if x->>'status'<>'closed' then raise exception 'Late vote not identified';end if;
 update public.rounds set debate_phase='finished' where id=rd;
 if private.limbo_blocked(room,u1) then raise exception 'Finished debate still blocks';end if;
 perform set_config('request.jwt.claim.sub','00000000-0080-4000-8000-000000000099',true);
 failed:=false;begin perform private.limbo_state(rd);exception when others then failed:=true;end;
 if not failed then raise exception 'Non-member read allowed';end if;
 if has_function_privilege('anon','public.propose_debate_limbo(bigint,text,integer)','execute') or has_table_privilege('authenticated','private.debate_limbo_proposals','select') then raise exception 'Incorrect privileges';end if;
 raise notice 'PASS R80: sizes, automatic YES, target vote, majority, locks, return guard, expiry, host transfer, late vote, end, access';
end $test$;
rollback;
