create table if not exists public.debate_dilemma_proposals (
 id bigint generated by default as identity primary key,
 room_id bigint not null references public.rooms(id) on delete cascade,
 dilemma_id bigint references public.dilemmas(id),
 question text not null,
 option_a text not null,
 option_b text not null,
 category text not null default 'PERSONALIZADO',
 status text not null default 'open' check(status in ('open','accepted','rejected','launched')),
 proposed_by uuid not null,
 created_at timestamptz not null default now()
);
create table if not exists public.debate_dilemma_proposal_votes (
 proposal_id bigint not null references public.debate_dilemma_proposals(id) on delete cascade,
 user_id uuid not null,
 choice boolean not null,
 primary key(proposal_id,user_id)
);
create index if not exists debate_proposal_room_idx on public.debate_dilemma_proposals(room_id,id desc);
alter table public.debate_dilemma_proposals enable row level security;
alter table public.debate_dilemma_proposal_votes enable row level security;
revoke all on public.debate_dilemma_proposals,public.debate_dilemma_proposal_votes from anon,authenticated;
create or replace function public.debate_proposal_state(p_room bigint) returns jsonb
language plpgsql security definer set search_path=public as $$
declare p public.debate_dilemma_proposals; r public.rooms; yes_count integer; no_count integer; total integer; mine boolean;
begin
 select * into r from rooms where id=p_room;
 if r.id is null or auth.uid() is null or not exists(select 1 from players where room_id=p_room and user_id=auth.uid() and abandoned_at is null) then raise exception 'No perteneces a esta mesa'; end if;
 if r.mode <> 'debate' or r.status <> 'waiting' then return '{}'::jsonb; end if;
 select * into p from debate_dilemma_proposals where room_id=p_room and status in ('open','accepted') order by id desc limit 1;
 if p.id is null then return jsonb_build_object('rejected_ids',coalesce((select jsonb_agg(dilemma_id) from debate_dilemma_proposals where room_id=p_room and status='rejected' and dilemma_id is not null),'[]'::jsonb)); end if;
 select count(*) filter(where choice),count(*) filter(where not choice) into yes_count,no_count from debate_dilemma_proposal_votes where proposal_id=p.id;
 select count(*) into total from players where room_id=p_room and abandoned_at is null and presence='present';
 select choice into mine from debate_dilemma_proposal_votes where proposal_id=p.id and user_id=auth.uid();
 return jsonb_build_object('id',p.id,'status',p.status,'dilemma_id',p.dilemma_id,'question',p.question,'option_a',p.option_a,'option_b',p.option_b,'category',p.category,'yes',yes_count,'no',no_count,'total',total,'my_vote',mine,'has_voted',exists(select 1 from debate_dilemma_proposal_votes where proposal_id=p.id and user_id=auth.uid()),'rejected_ids',coalesce((select jsonb_agg(dilemma_id) from debate_dilemma_proposals where room_id=p_room and status='rejected' and dilemma_id is not null),'[]'::jsonb));
end $$;
create or replace function public.debate_recount_proposal(p_id bigint) returns void
language plpgsql security definer set search_path=public as $$
declare p public.debate_dilemma_proposals; total integer; yes_count integer; votes_count integer;
begin
 select * into p from debate_dilemma_proposals where id=p_id for update;
 if p.status <> 'open' then return; end if;
 select count(*) into total from players where room_id=p.room_id and abandoned_at is null and presence='present';
 select count(*) filter(where v.choice), count(*) into yes_count,votes_count from debate_dilemma_proposal_votes v join players pl on pl.user_id=v.user_id and pl.room_id=p.room_id where v.proposal_id=p_id and pl.abandoned_at is null and pl.presence='present';
 if yes_count > total/2 then update debate_dilemma_proposals set status='accepted' where id=p_id;
 elsif votes_count>=total then update debate_dilemma_proposals set status='rejected' where id=p_id;
 end if;
end $$;
create or replace function public.debate_propose_dilemma(p_room bigint,p_dilemma bigint default null,p_question text default null,p_a text default null,p_b text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare r public.rooms; d public.dilemmas; new_id bigint;
begin
 select * into r from rooms where id=p_room for update;
 if r.id is null or r.mode <> 'debate' or r.status <> 'waiting' or auth.uid() is null or not exists(select 1 from players where room_id=p_room and user_id=auth.uid() and player_id=r.host_id and abandoned_at is null and presence='present') then raise exception 'Solo el anfitrión puede proponer'; end if;
 if exists(select 1 from debate_dilemma_proposals where room_id=p_room and status in ('open','accepted')) then raise exception 'Ya hay un dilema propuesto'; end if;
 if p_dilemma is not null then
  select * into d from dilemmas where id=p_dilemma and active=true and audience='teen';
  if d.id is null then raise exception 'Dilema no disponible'; end if;
  if exists(select 1 from debate_dilemma_proposals where room_id=p_room and dilemma_id=p_dilemma and status='rejected') then raise exception 'Este dilema ya fue descartado'; end if;
  p_question:=d.question;p_a:=d.option_a;p_b:=d.option_b;
 else
  if length(trim(coalesce(p_question,''))) not between 1 and 240 or length(trim(coalesce(p_a,''))) not between 1 and 240 or length(trim(coalesce(p_b,''))) not between 1 and 240 then raise exception 'Completa la pregunta y ambas opciones'; end if;
 end if;
 insert into debate_dilemma_proposals(room_id,dilemma_id,question,option_a,option_b,category,proposed_by)
 values(p_room,p_dilemma,trim(p_question),trim(p_a),trim(p_b),coalesce(d.category,'PERSONALIZADO'),auth.uid()) returning id into new_id;
 insert into debate_dilemma_proposal_votes(proposal_id,user_id,choice) values(new_id,auth.uid(),true);
 perform debate_recount_proposal(new_id);
 return new_id;
end $$;
create or replace function public.debate_vote_proposal(p_id bigint,p_yes boolean) returns void
language plpgsql security definer set search_path=public as $$
declare p public.debate_dilemma_proposals; r public.rooms;
begin
 select * into p from debate_dilemma_proposals where id=p_id for update;
 select * into r from rooms where id=p.room_id;
 if p.id is null or p.status <> 'open' or r.status <> 'waiting' or auth.uid() is null or not exists(select 1 from players where room_id=p.room_id and user_id=auth.uid() and abandoned_at is null and presence='present') then raise exception 'Votación cerrada'; end if;
 insert into debate_dilemma_proposal_votes(proposal_id,user_id,choice) values(p_id,auth.uid(),p_yes);
 perform debate_recount_proposal(p_id);
end $$;
create or replace function public.debate_start_approved(p_id bigint) returns bigint
language plpgsql security definer set search_path=public as $$
declare p public.debate_dilemma_proposals; r public.rooms; dilemma bigint; round_id bigint;
begin
 select * into p from debate_dilemma_proposals where id=p_id;
 select * into r from rooms where id=p.room_id for update;
 if p.id is null or p.status <> 'accepted' or r.status <> 'waiting' or r.mode <> 'debate' or auth.uid() is null or not exists(select 1 from players where room_id=r.id and user_id=auth.uid() and player_id=r.host_id and abandoned_at is null and presence='present') then raise exception 'Dilema sin aprobar o anfitrión no autorizado'; end if;
 dilemma:=p.dilemma_id;
 if dilemma is null then
  insert into dilemmas(audience,category,intensity,question,option_a,option_b,active)
  values('custom','PERSONALIZADO',1,p.question,p.option_a,p.option_b,true) returning id into dilemma;
 end if;
 insert into rounds(room_id,round_number,dilemma_id,status,started_at)
 values(r.id,coalesce((select max(round_number) from rounds where room_id=r.id),0)+1,dilemma,'voting',now()) returning id into round_id;
 update rooms set status='playing' where id=r.id;
 update debate_dilemma_proposals set status='launched' where id=p_id;
 return round_id;
end $$;
revoke all on function public.debate_recount_proposal(bigint) from public,anon,authenticated;
grant execute on function public.debate_proposal_state(bigint),public.debate_propose_dilemma(bigint,bigint,text,text,text),public.debate_vote_proposal(bigint,boolean),public.debate_start_approved(bigint) to authenticated;