create table if not exists public.debate_assistant_guides (
 id bigint generated by default as identity primary key,
 round_id bigint not null references public.rounds(id) on delete cascade,
 user_id uuid not null,
 cycle_number bigint not null,
 choice text not null check (choice in ('A','B')),
 status text not null default 'pending' check (status in ('pending','ready')),
 guide jsonb,
 mode text,
 created_at timestamptz not null default now(),
 unique (round_id,user_id,cycle_number,choice)
);
create index if not exists debate_assistant_guides_user_idx on public.debate_assistant_guides(user_id,round_id);
alter table public.debate_assistant_guides enable row level security;
revoke all on public.debate_assistant_guides from anon,authenticated;

create or replace function public.prepare_debate_assistant(p_round_id bigint)
returns jsonb language plpgsql security definer set search_path to ''
as $function$
declare v_room bigint;v_dilemma bigint;v_phase text;v_cycle bigint;v_paused boolean;v_choice text;
 v_question text;v_a text;v_b text;v_twist text;v_new bigint;v_guide public.debate_assistant_guides%rowtype;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 select room_id,dilemma_id,debate_phase,vote_cycle,paused
 into v_room,v_dilemma,v_phase,v_cycle,v_paused
 from public.rounds where id=p_round_id for update;
 if v_room is null or v_phase<>'debate' or v_paused then raise exception 'Assistant unavailable'; end if;
 if not exists(select 1 from public.players where room_id=v_room and user_id=auth.uid()
   and abandoned_at is null and presence='present') then raise exception 'Not active'; end if;
 if exists(select 1 from public.debate_optional_revote_windows
  where round_id=p_round_id and vote_cycle=v_cycle and closed_at is null)
 then raise exception 'Wait for the vote to finish'; end if;
 select choice into v_choice from public.debate_vote_cycles
 where round_id=p_round_id and cycle_number=v_cycle and user_id=auth.uid() limit 1;
 if v_choice not in ('A','B') then raise exception 'Vote before opening the assistant'; end if;
 select question,option_a,option_b into v_question,v_a,v_b from public.dilemmas where id=v_dilemma;
 if v_question is null then raise exception 'Dilemma unavailable'; end if;
 select text into v_twist from public.debate_twists where round_id=p_round_id order by id desc limit 1;
 insert into public.debate_assistant_guides(round_id,user_id,cycle_number,choice)
 values(p_round_id,auth.uid(),v_cycle,v_choice)
 on conflict(round_id,user_id,cycle_number,choice) do nothing returning id into v_new;
 select * into v_guide from public.debate_assistant_guides
 where round_id=p_round_id and user_id=auth.uid() and cycle_number=v_cycle and choice=v_choice for update;
 if v_new is null and v_guide.status='pending' and v_guide.created_at<now()-interval '45 seconds' then
   update public.debate_assistant_guides set created_at=now() where id=v_guide.id;
 elsif v_new is null and v_guide.status='pending' then
   return jsonb_build_object('status','pending');
 end if;
 return jsonb_build_object('status',v_guide.status,'guide',v_guide.guide,'mode',v_guide.mode,
   'question',v_question,'option_a',v_a,'option_b',v_b,'choice',v_choice,
   'twist',v_twist,'cycle',v_cycle);
end $function$;

create or replace function public.save_debate_assistant(p_round_id bigint,p_cycle bigint,p_choice text,p_guide jsonb,p_mode text)
returns boolean language plpgsql security definer set search_path to ''
as $function$
declare v_room bigint;v_phase text;v_cycle bigint;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if p_mode not in ('IA','BASICA') or p_guide is null or length(p_guide::text)>6000
 or jsonb_typeof(p_guide)<>'object' then raise exception 'Invalid guide'; end if;
 select room_id,debate_phase,vote_cycle into v_room,v_phase,v_cycle from public.rounds where id=p_round_id;
 if v_room is null or v_phase<>'debate' or v_cycle<>p_cycle then raise exception 'Round changed'; end if;
 if not exists(select 1 from public.players where room_id=v_room and user_id=auth.uid()
   and abandoned_at is null and presence='present') then raise exception 'Not active'; end if;
 update public.debate_assistant_guides set guide=p_guide,mode=p_mode,status='ready'
 where round_id=p_round_id and user_id=auth.uid() and cycle_number=p_cycle and choice=p_choice and (status='pending' or (mode='BASICA' and p_mode='IA'));
 return found;
end $function$;
revoke all on function public.prepare_debate_assistant(bigint) from public,anon,authenticated;
revoke all on function public.save_debate_assistant(bigint,bigint,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.prepare_debate_assistant(bigint) to authenticated;
grant execute on function public.save_debate_assistant(bigint,bigint,text,jsonb,text) to authenticated;